In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [7]:
df = pd.read_csv('ex2data1.txt', header=None)
df.head()

0          1  2
0  34.623660  78.024693  0
1  30.286711  43.894998  0
2  35.847409  72.902198  0
3  60.182599  86.308552  1
4  79.032736  75.344376  1

In [8]:
X = df.iloc[:, :-1]
X.head(3)

0          1
0  34.623660  78.024693
1  30.286711  43.894998
2  35.847409  72.902198

In [9]:
y = df.iloc[:, -1]

In [10]:
y[:3]

0    0
1    0
2    0
Name: 2, dtype: int64

In [11]:
X = np.c_[np.ones((X.shape[0], 1)), X]
X[:10]

array([[ 1.        , 34.62365962, 78.02469282],
       [ 1.        , 30.28671077, 43.89499752],
       [ 1.        , 35.84740877, 72.90219803],
       [ 1.        , 60.18259939, 86.3085521 ],
       [ 1.        , 79.03273605, 75.34437644],
       [ 1.        , 45.08327748, 56.31637178],
       [ 1.        , 61.10666454, 96.51142588],
       [ 1.        , 75.02474557, 46.55401354],
       [ 1.        , 76.0987867 , 87.42056972],
       [ 1.        , 84.43281996, 43.53339331]])

In [12]:
y = y[:, np.newaxis]
y[:10]

array([[0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1]], dtype=int64)

In [13]:
theta = np.zeros((X.shape[1], 1))
theta

array([[0.],
       [0.],
       [0.]])

In [14]:
z = np.dot(X, theta)
z[:5]

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [15]:
h = 1/(1+np.exp(-z))
h[:5]

array([[0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5]])

In [16]:
m = X.shape[0]
m

100

In [17]:
cost = -(1/m)*np.sum(y*np.log(h) + (1-y)*np.log(1-h))
cost

0.6931471805599453

In [18]:
grad = (1/m) * np.dot(X.T, (h-y))
grad

array([[ -0.1       ],
       [-12.00921659],
       [-11.26284221]])

In [19]:
def sigmoid(x, theta):
    z= np.dot(x, theta)
    return 1/(1+np.exp(-z))

In [20]:
def hypothesis(theta, x):
    return sigmoid(x, theta)

In [21]:
def cost_function(theta, x, y):
    m = X.shape[0]
    h = hypothesis(theta, x)
    return -(1/m)*np.sum(y*np.log(h) + (1-y)*np.log(1-h))

In [22]:
def gradient(theta, x, y):
    m = X.shape[0]
    h = hypothesis(theta, x)
    return (1/m) * np.dot(X.T, (h-y))    

In [23]:
from scipy.optimize import minimize,fmin_tnc
def fit(x, y, theta):
    opt_weights = fmin_tnc(func=cost_function, x0=theta, fprime=gradient, args=(x, y.flatten()))
    return opt_weights[0]
parameters = fit(X, y, theta)

In [27]:
parameters

array([-25.16131854,   0.20623159,   0.20147149])

In [28]:
h = hypothesis(parameters, X)

In [36]:
h

array([9.10339294e-02, 4.22589668e-05, 4.39088910e-02, 9.90424697e-01,
       9.98198750e-01, 1.07975521e-02, 9.98978138e-01, 4.23227057e-01,
       9.99710020e-01, 7.35387955e-01, 9.09674394e-01, 2.85967738e-02,
       9.99270142e-01, 9.99853945e-01, 1.56037085e-01, 9.80959345e-01,
       4.27716900e-01, 1.48789237e-01, 9.99706543e-01, 5.74280760e-01,
       6.68350391e-02, 9.98627244e-01, 7.41803067e-03, 1.01155397e-04,
       9.91878247e-01, 8.55048631e-01, 6.00298722e-01, 8.65184829e-01,
       9.23893094e-02, 1.68289210e-02, 8.97130763e-01, 9.81037346e-01,
       1.54911024e-01, 3.91938615e-01, 7.41289966e-02, 3.31107865e-02,
       8.52267971e-01, 9.87564309e-01, 2.03987785e-01, 4.95799793e-02,
       9.70300369e-01, 6.11823902e-03, 9.99461484e-01, 5.02285122e-01,
       4.48870646e-03, 1.37023865e-01, 9.92991802e-01, 9.99996181e-01,
       9.99204915e-01, 9.99990761e-01, 9.98106782e-01, 9.99500487e-01,
       9.05015908e-01, 2.80614817e-03, 8.52272267e-03, 5.28909917e-02,
      

In [42]:
def predict(h):
    h1 = []
    for i in h:
        if i>=0.5:
            h1.append(1)
        else:
            h1.append(0)
    return h1
y_pred = predict(h)

In [45]:
accuracy = 0
for i in range(0, len(y_pred)):
    if y_pred[i] == y[i]:
        accuracy += 1
accuracy/len(y)

0.89