In [7]:
import pandas as pd
import numpy as np

In [8]:
xl = pd.ExcelFile('ex3d1.xlsx')
df = pd.read_excel(xl, 'X', header=None)
df.head()

0    1    2    3    4    5    6    7    8    9    ...  390  391  392  393  \
0    0    0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
1    0    0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
2    0    0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
3    0    0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
4    0    0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   

   394  395  396  397  398  399  
0  0.0  0.0  0.0  0.0  0.0    0  
1  0.0  0.0  0.0  0.0  0.0    0  
2  0.0  0.0  0.0  0.0  0.0    0  
3  0.0  0.0  0.0  0.0  0.0    0  
4  0.0  0.0  0.0  0.0  0.0    0  

[5 rows x 400 columns]

In [9]:
y = pd.read_excel(xl, 'y', hearder = None)
y.head(5)

10
0  10
1  10
2  10
3  10
4  10

In [10]:
df = df.iloc[1:]

In [11]:
y = y.iloc[:, 0]

In [12]:
y[:5]

0    10
1    10
2    10
3    10
4    10
Name: 10, dtype: int64

In [13]:
y.unique()

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9], dtype=int64)

In [14]:
y1 = np.zeros([df.shape[0], len(y.unique())])
y1 = pd.DataFrame(y1)

In [16]:
len(df)

4999

In [17]:
len(y)

4999

In [18]:
y.unique()

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9], dtype=int64)

In [19]:
for i in range(0, len(y.unique())):
    for j in range(0, len(y1)):
        if y[j] == y.unique()[i]:
            y1.iloc[j, i] = 1
        else: 
            y1.iloc[j, i] = 0
y1.head()           

0    1    2    3    4    5    6    7    8    9
0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [20]:
y1.tail()

0    1    2    3    4    5    6    7    8    9
4994  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
4995  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
4996  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
4997  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
4998  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0

In [21]:
y1.shape

(4999, 10)

In [22]:
theta = np.zeros([df.shape[1]+1, y1.shape[1]])

In [23]:
theta.shape

(401, 10)

In [24]:
theta.shape[0]

401

In [26]:
X = pd.concat([pd.Series(1, index=df.index, name='00'), df], axis=1)

In [27]:
X.shape

(4999, 401)

In [103]:
theta = np.ones(df.shape[1]+1)
def hypothesis(theta, X):
    return 1 / (1 + np.exp(-(np.dot(theta, X.T)))) - 0.0000001

In [104]:
theta.shape

(401,)

In [105]:
h = hypothesis(theta, X)

In [106]:
def cost(X, y, theta):
    y1 = hypothesis(X, theta)
    return -(1/len(X)) * np.sum(y*np.log(y1) + (1-y)*np.log(1-y1))    

In [107]:
theta = pd.DataFrame(theta)

In [108]:
type(theta.iloc[:,0])

pandas.core.series.Series

In [109]:
def gradient_descent(X, y, theta, alpha, epochs):
    m = len(X)
    #cost = [[] for i in range(10)]
    for i in range(0, epochs):
        for j in range(0, 10):
            theta = pd.DataFrame(theta)
            h = hypothesis(theta.iloc[:,j], X)
            for k in range(0, theta.shape[0]):
                theta.iloc[k, j] -= (alpha/m) * np.sum((h-y.iloc[:, j])*X.iloc[:, k])
            theta = pd.DataFrame(theta)
            #c =cost(X, y.iloc[:, j], theta.iloc[:,j])
            #cost[j].append(c)
    return theta           

In [120]:
theta = np.zeros([df.shape[1]+1, y1.shape[1]])
theta = gradient_descent(X, y1, theta, 0.02, 1500)

In [121]:
theta

0             1             2             3             4  \
0   -4.670397e-01 -5.859904e-02 -4.271863e-01 -4.450491e-01 -1.858058e-01   
1    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
2    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
3   -1.156953e-07  2.463390e-06 -2.121998e-07 -3.781896e-07 -1.874859e-07   
4    1.385651e-06 -2.213616e-05  2.493637e-06  2.006479e-08  2.034727e-06   
5    9.422436e-06 -2.055303e-05  2.506376e-06  6.398609e-05  1.311073e-05   
6   -1.294902e-04 -1.854882e-04 -1.034142e-04  2.446371e-04 -1.565561e-04   
7   -3.254324e-04 -1.042411e-04 -3.353331e-04 -5.303653e-04 -3.969055e-04   
8   -1.157817e-04  1.791082e-04 -4.754270e-04 -3.105367e-04 -3.275615e-04   
9    1.295912e-05 -3.296245e-06  1.690064e-05  3.092757e-05  6.039164e-06   
10  -4.970363e-05  1.646721e-05 -4.360837e-06  5.657267e-06  5.135668e-04   
11  -8.144230e-06  1.352233e-06 -4.487144e-06  6.441484e-06  1.802013e-04   
12   8.273879e-06  1.219527e-05  1.797067e-05 -8.138453e-05 -4.285870e-05   
13   2.212612e-05  2.810481e-05  3.921887e-05 -2.342808e-04  5.207572e-05   
14   1.222290e-04  1.929603e-05  3.155727e-05 -1.537059e-04  6.105041e-05   
15   1.312412e-04  4.284898e-05  1.515523e-05 -3.609523e-04  4.631903e-05   
16   4.812101e-05  3.887868e-05  2.982896e-05 -4.187788e-04  5.157922e-05   
17   1.151484e-05  1.085556e-05  2.231956e-05 -1.398850e-04  1.340066e-05   
18   3.253800e-07  1.598234e-07 -1.009549e-06  1.167676e-06 -8.666104e-07   
19  -1.503956e-07 -1.232929e-07 -1.185906e-07  1.279531e-06 -6.635475e-08   
20   0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
21  -1.400115e-08 -9.751583e-09 -4.382086e-08 -2.031069e-08 -1.027531e-07   
22  -3.249897e-08 -3.192325e-07  2.168555e-07  2.311447e-06  1.386473e-06   
23   1.356902e-06 -2.658135e-05  5.400033e-06  3.262820e-06  3.406017e-06   
24   7.766549e-06  2.933663e-04 -1.289633e-05 -2.470342e-04 -4.127901e-05   
25   8.268241e-05  3.720564e-04 -3.327878e-05 -4.964129e-04 -1.503769e-04   
26  -2.455160e-04 -2.479967e-04 -2.896432e-04 -7.423084e-04 -6.640603e-04   
27  -1.265304e-03 -6.800007e-04 -1.587642e-03 -1.673766e-03 -2.680931e-03   
28  -9.933906e-04 -3.061127e-04 -1.672622e-03 -8.527238e-04 -2.559059e-03   
29  -4.700446e-04 -9.203746e-05 -4.356693e-04 -8.240637e-04 -1.988041e-04   
..            ...           ...           ...           ...           ...   
371 -6.674639e-03  6.882933e-05 -1.273097e-03 -2.630607e-03 -3.581863e-03   
372 -8.532064e-03 -1.761686e-03  1.408266e-02 -6.038241e-03 -3.115033e-03   
373 -9.569557e-03 -5.636199e-03  3.660586e-02 -8.956340e-03 -3.491477e-03   
374 -3.014461e-03 -3.552539e-03  2.791405e-02 -5.401426e-03 -2.481285e-03   
375 -2.710358e-03 -2.397320e-04  1.508153e-02 -3.726838e-03 -1.378545e-03   
376 -7.834102e-04  1.452720e-04  9.903805e-03 -1.637745e-03 -5.951665e-05   
377  2.665338e-05 -6.075949e-05  3.355250e-03 -3.435015e-04  5.396248e-04   
378  3.256004e-05  4.698082e-05 -3.860254e-04  8.710432e-05 -1.977149e-04   
379  5.196685e-06  1.739976e-05  2.128252e-06  1.532513e-05 -3.858357e-05   
380  2.449870e-07  2.180985e-06  5.276310e-07  4.936667e-07  5.583201e-06   
381  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
382 -1.075395e-06 -6.389017e-07  4.250561e-07 -1.325280e-06 -6.451006e-07   
383  1.770359e-06 -9.403098e-06 -1.351963e-06  1.256591e-05  1.672721e-05   
384  1.145308e-04  1.780504e-04 -1.001026e-05  1.239424e-04 -3.975811e-05   
385 -1.818563e-05 -1.746799e-04 -4.387656e-04 -1.485916e-03 -8.455915e-04   
386 -6.443465e-04 -9.504525e-05 -9.940267e-04 -2.356185e-03 -4.153771e-04   
387 -1.748778e-04  1.617573e-04 -1.238858e-04 -2.847368e-04  1.741293e-04   
388  2.422588e-04 -1.506223e-06  7.881181e-05  2.380713e-04 -7.172234e-05   
389  1.416570e-04  2.211592e-05 -1.198544e-04  6.833512e-05 -5.389890e-05   
390  1.059165e-04  9.608056e-05  2.202741e-04 -4.197455e-05  1.245018e-04   
391 -3.09432

In [122]:
def predict(X, y):
    #theta1 = gradient_descent(X, y, theta, alpha, epochs)
    accuracy = 0
    for i in range(10):
        h = hypothesis(theta1.iloc[:,j], X)
        for n in range(0, len(h)):
            if h[n] >= 0.5 and y1.iloc[n, i] == 1:
                accuracy += 1
            elif h[n] < 0.5 and y1.iloc[n, i] == 0:
                accuracy += 1
    return accuracy       
        

In [123]:
theta = pd.DataFrame(theta)
hypothesis(theta.iloc[:,9], X)

array([1.25206134e-04, 2.84079087e-04, 8.73560112e-05, ...,
       5.73199856e-01, 2.11109525e-01, 4.04368766e-03])

In [124]:
output = []
for i in range(0, 10):
    theta1 = pd.DataFrame(theta)
    h = hypothesis(theta1.iloc[:,i], X)
    output.append(h)
output=pd.DataFrame(output)

In [125]:
output

0         1         2             3         4         5         6     \
0  0.996150  0.010573  0.598520  9.989982e-01  0.997692  0.922469  0.932535   
1  0.000081  0.000009  0.000005  2.330011e-07  0.000002  0.000004  0.005858   
2  0.000205  0.000308  0.001013  7.042428e-05  0.000593  0.000013  0.802239   
3  0.000800  0.000825  0.000242  1.618547e-03  0.000046  0.004492  0.352147   
4  0.000148  0.000064  0.000122  1.001990e-04  0.000160  0.000091  0.006113   
5  0.076269  0.017289  0.005766  3.378000e-02  0.016528  0.002213  0.057534   
6  0.000167  0.004093  0.011704  2.418944e-06  0.000039  0.000048  0.000952   
7  0.002474  0.000612  0.000696  3.058105e-03  0.004356  0.000200  0.021843   
8  0.000145  0.027876  0.000416  2.513581e-03  0.016044  0.000732  0.262186   
9  0.000125  0.000284  0.000087  4.472931e-04  0.003097  0.000516  0.001190   

           7         8             9     ...      4989      4990      4991  \
0  1.608033e-01  0.838501  6.529952e-01  ...  0.002443  0.000209  0.000261   
1  2.316491e-08  0.000020  5.819819e-07  ...  0.000183  0.002656  0.001078   
2  6.393464e-05  0.000233  8.017950e-05  ...  0.000555  0.001389  0.001788   
3  4.837361e-03  0.087413  5.676880e-03  ...  0.963414  0.000209  0.000249   
4  2.565903e-05  0.000109  5.348489e-05  ...  0.000077  0.112132  0.088464   
5  1.578181e-02  0.063912  2.218375e-01  ...  0.059000  0.005716  0.000646   
6  7.653373e-04  0.000113  6.662352e-04  ...  0.000145  0.004958  0.000998   
7  3.859526e-04  0.001469  7.430382e-04  ...  0.002648  0.034546  0.030160   
8  6.876312e-03  0.001507  1.374031e-02  ...  0.009143  0.103219  0.154535   
9  6.397821e-04  0.000377  5.678806e-04  ...  0.005828  0.906382  0.736391   

       4992      4993      4994      4995      4996      4997      4998  
0  0.000506  0.001522  0.002278  0.001887  0.001589  0.000317  0.171189  
1  0.000061  0.000287  0.000583  0.000003  0.008583  0.000066  0.000008  
2  0.000842  0.001626  0.004107  0.009041  0.005316  0.000005  0.024396  
3  0.000003  0.000002  0.031804  0.000004  0.063966  0.000001  0.000134  
4  0.037436  0.025472  0.473967  0.018584  0.285876  0.087510  0.034204  
5  0.000166  0.000164  0.020281  0.000040  0.191378  0.009109  0.000168  
6  0.001438  0.000226  0.014466  0.000310  0.059865  0.000197  0.009210  
7  0.039977  0.117898  0.011892  0.033810  0.006390  0.095094  0.088300  
8  0.135045  0.029102  0.042511  0.124841  0.033172  0.002596  0.008577  
9  0.417320  0.275664  0.905152  0.125281  0.573200  0.211110  0.004044  

[10 rows x 4999 columns]

In [126]:
output.iloc[2, 50]

0.1298007475503566

In [127]:
accuracy = 0
for col in range(0, 10):
    for row in range(len(y1)):
        if y1.iloc[row, col] == 1 and output.iloc[col, row] >= 0.5:
            accuracy += 1
accuracy

3604

In [128]:
accuracy= accuracy/len(X)

In [129]:
accuracy

0.7209441888377676

In [6]:
import numpy as np


array([], dtype=int32)